// Re-export the generic helpers that ship directly inside database.ts
// (generated by `supabase gen types typescript`).
export type {
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  CompositeTypes,
} from "./database";
